server.port=8080
spring.application.name=langlearn-frontend
server.forward-headers-strategy=native

#live reload
spring.thymeleaf.cache=false
spring.devtools.livereload.enabled=true

backend.url=http://langlearn-backend-service:3000