#release configuration
#Thu Apr 23 23:33:54 CEST 2026
completedPhase=generate-release-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.com.jakkas\:langlearn=0.0.3-SNAPSHOT
project.dev.com.jakkas\:langlearn-backend=0.0.3-SNAPSHOT
project.dev.com.jakkas\:langlearn-db=0.0.3-SNAPSHOT
project.dev.com.jakkas\:langlearn-frontend=0.0.3-SNAPSHOT
project.rel.com.jakkas\:langlearn=0.0.2
project.rel.com.jakkas\:langlearn-backend=0.0.2
project.rel.com.jakkas\:langlearn-db=0.0.2
project.rel.com.jakkas\:langlearn-frontend=0.0.2
project.scm.com.jakkas\:langlearn-backend.empty=true
project.scm.com.jakkas\:langlearn-db.empty=true
project.scm.com.jakkas\:langlearn-frontend.empty=true
project.scm.com.jakkas\:langlearn.connection=scm\:git\:git@github.com\:ToNieKuba1234/LangLearn.git
project.scm.com.jakkas\:langlearn.developerConnection=scm\:git\:git@github.com\:ToNieKuba1234/LangLearn.git
project.scm.com.jakkas\:langlearn.tag=0.0.1
project.scm.com.jakkas\:langlearn.url=https\://github.com/ToNieKuba1234/LangLearn
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=\\
scm.tagNameFormat=v@{project.version}
scm.url=scm\:git\:git@github.com\:ToNieKuba1234/LangLearn.git
