spring.application.name=langlearn
spring.datasource.url=jdbc:postgresql://localhost:5432/langlearn_db
spring.datasource.username=admin
spring.datasource.password=password123
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.data-locations=classpath:import.sql
spring.thymeleaf.cache=false