apiVersion: apps/v1
kind: Deployment
metadata:
  name: langlearn-db-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langlearn-db
  template:
    metadata:
      labels:
        app: langlearn-db
    spec:
      containers:
      - name: db
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          value: langlearn
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: password123

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: langlearn-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langlearn-backend
  template:
    metadata:
      labels:
        app: langlearn-backend
    spec:
      imagePullSecrets:
      - name: nexus-registry
      containers:
      - name: backend
        image: 192.168.53.53:8081/docker-hosted/langlearn-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://langlearn-db-service:5432/langlearn
        - name: SPRING_DATASOURCE_USERNAME
          value: admin
        - name: SPRING_DATASOURCE_PASSWORD
          value: password123
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: langlearn-frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langlearn-frontend
  template:
    metadata:
      labels:
        app: langlearn-frontend
    spec:
      imagePullSecrets:
      - name: nexus-registry
      containers:
      - name: frontend
        image: 192.168.53.53:8081/docker-hosted/langlearn-frontend:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"