server.port=3000
spring.application.name=langlearn-backend
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:postgresql://langlearn-db-service:5432/langlearn
spring.datasource.username=user
spring.datasource.password=pass

spring.jpa.show-sql=true


spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false


spring.jpa.hibernate.ddl-auto=validate